var annotated_dup =
[
    [ "BreakableWall", "d6/df4/class_breakable_wall.html", "d6/df4/class_breakable_wall" ],
    [ "CameraManager", "d2/d23/class_camera_manager.html", "d2/d23/class_camera_manager" ],
    [ "character_line", "df/d1a/classcharacter__line.html", "df/d1a/classcharacter__line" ],
    [ "Conversation", "d2/d94/class_conversation.html", "d2/d94/class_conversation" ],
    [ "Dialogue", "d0/d9d/class_dialogue.html", "d0/d9d/class_dialogue" ],
    [ "DialogueTest", "dd/d62/class_dialogue_test.html", "dd/d62/class_dialogue_test" ],
    [ "Door", "da/d30/class_door.html", "da/d30/class_door" ],
    [ "Effect", "d6/d58/class_effect.html", "d6/d58/class_effect" ],
    [ "FadeController", "d3/dd7/class_fade_controller.html", "d3/dd7/class_fade_controller" ],
    [ "FixedResoultion", "d3/d6d/class_fixed_resoultion.html", "d3/d6d/class_fixed_resoultion" ],
    [ "Hungerness", "db/d74/class_hungerness.html", "db/d74/class_hungerness" ],
    [ "IInteractable", "d2/df1/interface_i_interactable.html", "d2/df1/interface_i_interactable" ],
    [ "Interaction", "d3/d8e/class_interaction.html", "d3/d8e/class_interaction" ],
    [ "Item", "dc/d32/class_item.html", "dc/d32/class_item" ],
    [ "ItemDatabase", "d0/dc6/class_item_database.html", "d0/dc6/class_item_database" ],
    [ "ItemGainable", "d5/dc8/class_item_gainable.html", "d5/dc8/class_item_gainable" ],
    [ "ItemTool", "d3/df3/class_item_tool.html", "d3/df3/class_item_tool" ],
    [ "Movement", "d1/de2/class_movement.html", "d1/de2/class_movement" ],
    [ "MovingPlatform", "df/d42/class_moving_platform.html", "df/d42/class_moving_platform" ],
    [ "PhoneController", "db/dfb/class_phone_controller.html", "db/dfb/class_phone_controller" ],
    [ "PlayerMovement", "d0/d3d/class_player_movement.html", "d0/d3d/class_player_movement" ],
    [ "StageManager", "da/de4/class_stage_manager.html", "da/de4/class_stage_manager" ],
    [ "Stone", "d7/d17/class_stone.html", "d7/d17/class_stone" ],
    [ "StoneTrigger", "d5/df7/class_stone_trigger.html", "d5/df7/class_stone_trigger" ],
    [ "Switch", "d9/d47/class_switch.html", "d9/d47/class_switch" ],
    [ "Switch1_1", "d2/da6/class_switch1__1.html", "d2/da6/class_switch1__1" ],
    [ "Tool", "da/db7/class_tool.html", "da/db7/class_tool" ],
    [ "TruckController", "d2/d37/class_truck_controller.html", "d2/d37/class_truck_controller" ],
    [ "TutorialManager", "d6/d14/class_tutorial_manager.html", "d6/d14/class_tutorial_manager" ],
    [ "UI", "d8/de6/class_u_i.html", "d8/de6/class_u_i" ],
    [ "UITextScript", "da/d8d/class_u_i_text_script.html", "da/d8d/class_u_i_text_script" ]
];